### ISSUE TITLE
GemStone portability

### ISSUE THREAD

**Issue by pdebruic** [DuneSt/MaterialDesignLite#61]
I'm gonna submit a PR but here are the things I've noticed thus far:

Symbol>>#asClass - is DNU in GemStone

Symbols and Strings do not compare as equal in GemStone. e.g. #abc ~= 'abc' so in the Baseline we gotta change the symbols to strings as the file names are strings in GS.

**Comment by jecisc** [comment]
Thank you!

- Where is used #asClass? Is it in example or "real" code? #asClass should not be used in the code because it will be deprecated on future versions on Pharo. 

- Ok, no problem for changing the symbol as Strings in the baseline :)

If you want you can also add gemstone to the travis/appveyor configurations. If you don't know how to do it I'll do it.

**Comment by jecisc** [comment]
Even if we don't have a lot of test it will validate that everything loads fine :)

**Comment by jecisc** [comment]
We should also add a compatibility table to the README. 

It should includes Pharo 5, 6 and the gemstone versions where it will works. (I never used gemstone yet so if you could tell me what versions are covered it would be cool)

**Comment by pdebruic** [comment]
Hi - 

Sorry for the delay. 

#asClass is in the Baseline.


Other than that it just works.  Do you want me to make a PR for the Baseline or would you rather fix it?

**Comment by jecisc** [comment]
@pdebruic is `Smalltalk at: #MetacelloCypressBaselineProject` fine in all platform?

**Comment by jecisc** [comment]
Someone told me it was fine so I close this issue with this commit: 868f71bd6463ef0db5173e5bd8d6542d837a0220

If it is still not good feel free to open it again.

**Comment by pdebruic** [comment]
Yep.  As far as I know.
